// Registry of long-form SEO/GEO articles. Single source of truth for:
//   - The dynamic [slug] route's generateStaticParams.
//   - app/sitemap.ts URL enumeration with hreflang alternates.
//   - JSON-LD Article + FAQPage schema builders (below).
//   - public/llms.txt and llms-full.txt Articles sections.
//
// Adding a new article = one entry here + the matching i18n namespace in
// messages/{en,en-IN,ta,ta-IN}.json (parity enforced by check-i18n.mjs).
// No new route file required.

import type { Locale } from "@/i18n/routing";
import { BRAND_NAME } from "./brand";

export interface Article {
  /** URL slug under /[locale]/articles/[slug]. English-only, hyphenated. */
  slug: string;
  /** ISO date string — JSON-LD Article.datePublished. */
  publishedAt: string;
  /** ISO date string — JSON-LD Article.dateModified + sitemap lastModified. */
  updatedAt: string;
  /** Optional path under /public for a per-article OG image. Falls back to the
   *  landing OG when omitted. */
  ogImage?: string;
}

// Ordered most-important first; the order is what llms.txt and the footer
// Resources column use when listing.
export const ARTICLES: readonly Article[] = [
  {
    slug: "gstr-1-vs-gstr-3b-difference",
    publishedAt: "2026-05-22",
    updatedAt: "2026-05-22",
  },
  {
    slug: "business-health-dashboard-indian-smb",
    publishedAt: "2026-05-22",
    updatedAt: "2026-05-22",
  },
] as const;

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

// ─── JSON-LD schema builders (pure functions, no I/O) ──────────────────────
//
// These live here, not in components/marketing/json-ld.tsx, because they have
// no React dependency and need to be unit-testable without rendering. The
// rendering shim that emits <script type="application/ld+json"> sits in
// json-ld.tsx and just calls these.

export interface BuildArticleSchemaInput {
  article: Article;
  locale: Locale;
  siteUrl: string;
  headline: string;
  description: string;
}

export function buildArticleSchema(input: BuildArticleSchemaInput) {
  const { article, locale, siteUrl, headline, description } = input;
  const canonical = `${siteUrl}/${locale}/articles/${article.slug}`;
  // Per-article OG image when set, otherwise fall back to the landing OG.
  // The /og-image.png path is generated by app/[locale]/opengraph-image.tsx
  // — using a relative public path here would not work because schema.org
  // requires an absolute URL.
  const image = article.ogImage
    ? `${siteUrl}${article.ogImage}`
    : `${siteUrl}/og-image.png`;
  // schema.org inLanguage uses BCP-47. We bias both variants to India because
  // the articles are India-targeted (GSTR is India-only; the cockpit article
  // names Indian SMBs explicitly).
  const inLanguage = locale === "ta" ? "ta-IN" : "en-IN";

  return {
    "@context": "https://schema.org",
    "@type": "Article",
    headline,
    description,
    image,
    datePublished: article.publishedAt,
    dateModified: article.updatedAt,
    inLanguage,
    mainEntityOfPage: canonical,
    articleSection: "Guides",
    author: {
      "@type": "Organization",
      name: BRAND_NAME,
      url: siteUrl,
    },
    publisher: {
      "@type": "Organization",
      name: BRAND_NAME,
      url: siteUrl,
      logo: {
        "@type": "ImageObject",
        url: `${siteUrl}/logo.png`,
      },
    },
  } as const;
}

export function buildArticleFaqSchema(
  faq: ReadonlyArray<{ q: string; a: string }>,
) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faq.map((it) => ({
      "@type": "Question",
      name: it.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: it.a,
      },
    })),
  } as const;
}
